version: '3.8'

services:
  go-app:
    container_name: token-generator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8999:8080"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod

volumes:
  go-modules:
